title: シゴトのトビラの裏方は・・・今日も平和・・
email: info@shigotonotobira.com
description: >-
    派遣・求人情報サイト「シゴトのトビラ」です。
    三重県鈴鹿市のショッピングセンター鈴鹿ハンターの1Fで毎週月ー土 AM10:00-PC6:00営業してます。
baseurl: ""
url: "https://tobira-jobs.github.io"

# テーマは標準のminimaのみ
theme: minima

# プラグインを一旦すべて空にする（これが大事です！）
plugins: []

# 自分で作ったスタイルを適用する
custom_css: /assets/css/style.scss